swagger: "2.0"
info:
  description: "Listen to movies backend API service"
  version: "0.1.0"
  title: "Mavio API"
host: "localhost:3000"
basePath: "/api/v1"
tags:
- name: "Movie"
schemes:
- "http"
paths:
  /movie:
    post:
      tags:
      - "Movie"
      summary: "Creates a movie object"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New movie details"
        required: true
        schema:
          $ref: "#/definitions/MovieNew"
      responses:
        201:
          description: "The created movie info object"
          schema:
            $ref: "#/definitions/MovieInfo"
        400:
          description: "Invalid input body provided"
        409:
          description: "Movie is already in the database"
  /movie/{id}:
    get:
      tags:
      - "Movie"
      summary: "Gets the detailed info on a movie"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        description: "Movie ID"
        required: true
        type: "string"
      responses:
        200:
          description: "Movie found that matches the ID"
          schema:
            $ref: "#/definitions/MovieInfo"
        400:
          description: "Invalid query parameter provided"
        404:
          description: "Movie not found"
definitions:
  MovieInfo:
    type: "object"
    required:
    - "id"
    - "name"
    - "year"
    properties:
      id:
        type: "string"
        example: "9m2b5rplPm"
      name:
        type: "string"
        example: "A Beautiful Mind"
      year:
        type: "integer"
        example: 2001
  MovieNew:
    type: "object"
    required:
    - "name"
    - "year"
    properties:
      name:
        type: "string"
        example: "A Beautiful Mind"
      year:
        type: "integer"
        example: 2001